server:
  port: 8081

spring:
  application:
    name: boot-security

  # spring security配置
  security:
    user:
      name: tingyu
      password: tingyu

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?characterEncoding=UTF-8
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml