server:
  port: 8081

spring:
  application:
    name: boot-security

  # spring security配置
  security:
    user:
      name: tingyu
      password: tingyu

  # 数据库配置
  datasource:
    url: jdbc:mysql://47.111.5.242:3306/spring_security?characterEncoding=UTF-8
    username: fneelink
    password: '!LijianlonG147258'